networks:
    proxy-frontend:
      name: proxy-frontend
    backend:
      name: backend


services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    command:
      - --api.dashboard=true
      - --providers.docker.exposedbydefault=false
      - --api.insecure=true        # Aktivera Traefiks dashboard (ej för produktion)
      - --providers.docker=true    # Läs labels från Docker
      - --entrypoints.web.address=:80 # Entrypoint på port 80
      - --accesslog=true # Aktivera logg
     
    ports:
      - "80:80"
     # - "8080:8080"                  # Dashboard-kommenterat ut när det finns hostname
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     
    labels: # Har lagt label här för traefik container så att man kan nå det på "dashboard.localhost"
      - traefik.enable=true
      - traefik.docker.network=proxy-frontend
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`dashboard.localhost`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    networks:
      - proxy-frontend

  frontend1:
    build: ./frontend  
    image: frontend:latest 
    container_name: frontend1
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-frontend
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=Host(`frontend.localhost`)
      - traefik.http.services.frontend.loadbalancer.server.port=5000
    volumes:
      - ./frontend:/code
    depends_on: # Ordning av container aktivering:frontend är beroende av att backend är aktiverad för att den ska aktiveras..
    - backend
   
    networks:
      - proxy-frontend


  frontend2:
    build: ./frontend  
    image: frontend:latest 
    container_name: frontend2
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-frontend
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=Host(`frontend.localhost`)
      - traefik.http.services.frontend.loadbalancer.server.port=5000
    volumes:
      - ./frontend:/code
    
    depends_on: 
    - backend
   
    networks:
      - proxy-frontend
     
  frontend3:
    build: ./frontend  
    image: frontend:latest 
    container_name: frontend3
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-frontend
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.rule=Host(`frontend.localhost`)
      - traefik.http.services.frontend.loadbalancer.server.port=5000
    volumes:
      - ./frontend:/code
    
    depends_on:
    - backend
   
    networks:
      - proxy-frontend
     
  backend:
    build: ./backend 
    image: backend:latest 
    container_name: backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-frontend
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.rule=Host(`backend.localhost`) && PathPrefix(`/messages`)
      - traefik.http.services.backend.loadbalancer.server.port=5001
    volumes:
      - ./backend:/code
    depends_on: 
    - redis
    #ports: # Man kan ha port för backend om det inte går att spara i C:\Windows\System32\drivers\etc\hosts. Har lagt till PathPrefix till API request /messages..
    #- "5001:5001"
   
    networks:
      - proxy-frontend
      - backend
     
  
  redis:
    image: redislabs/redismod 
    container_name: redis-db
  
    
    networks:
     - backend 
  
